services:
  glance:
    image: glanceapp/glance
    container_name: glance
    ports:
      - "8080:8080"
    volumes:
      - ./glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --config /app/glance.yml
    restart: unless-stopped
